# Shared Enums
# SSOT for cross-domain enum values
# Used by: skills, documents, structure validators

# Pipeline phases (when work happens)
phases:
  - discovery       # Idea extraction, interviews
  - definition      # Requirements, user stories
  - design          # UX/UI design
  - architecture    # System design, API contracts
  - implementation  # Code, tests
  - delivery        # Deployment, docs, handoff
  - utility         # Cross-phase helpers

# Document/artifact categories (matches folder structure)
categories:
  - architecture    # System design, API contracts
  - backend         # Backend implementation
  - bugs            # Bug reports, debug reports
  - design          # UI/UX design, theming
  - discovery       # Feature briefs, roadmaps
  - frontend        # Frontend implementation
  - infrastructure  # Deployment, configs
  - product         # Requirements, user stories
  - project         # Project-wide docs
  - qa              # Test cases, test reports
  - refactoring     # Refactoring docs
  - specs           # Tech specs

# Document statuses
statuses:
  - draft           # Initial creation
  - in_progress     # Being worked on
  - review          # Ready for review
  - approved        # Approved by stakeholder
  - archived        # Completed and archived
  - obsolete        # Superseded by another doc

# Document lifecycles
lifecycles:
  - per-feature     # One document per feature
  - per-work-unit   # One document per work unit
  - living          # Continuously updated

# Lifecycle triggers (when events happen)
triggers:
  - on_activation       # When skill activates
  - on_create           # When document is created
  - on_complete         # When skill completes work
  - on_handoff          # When handing off to next skill
  - spec_approved       # Specification approved
  - design_complete     # Design phase complete
  - implementation_complete  # Implementation done
  - qa_signoff          # QA approved
  - user_approved       # User approved
  - user_approval       # Alias for user_approved (archives)
  - work_unit_opened    # New work unit started
  - work_unit_closed    # Work unit completed

# MCP servers (known integrations)
mcp_servers:
  - context7            # Documentation search
  - sky-cli             # Project management
  - github              # GitHub integration
  - figma               # Design system
  - telegram-docs       # Telegram API docs
