# Shared Runtime Enums
# SSOT for cross-domain values used during execution
# Used by: skills, documents, structure validators

# Document statuses (Title Case to match templates)
statuses:
  - Draft           # Initial creation
  - In Progress     # Being worked on
  - Review          # Ready for review
  - Approved        # Approved by stakeholder
  - Archived        # Completed and archived
  - Obsolete        # Superseded by another doc

# Document lifecycles
lifecycles:
  - per-feature     # One document per feature
  - per-work-unit   # One document per work unit
  - living          # Continuously updated

# Lifecycle triggers (when events happen)
triggers:
  - on_activation       # When skill activates
  - on_create           # When document is created
  - on_complete         # When skill completes work
  - on_handoff          # When handing off to next skill
  - spec_approved       # Specification approved
  - design_complete     # Design phase complete
  - implementation_complete  # Implementation done
  - qa_signoff          # QA approved
  - user_approved       # User approved
  - user_approval       # Alias for user_approved (archives)
  - work_unit_opened    # New work unit started
  - work_unit_closed    # Work unit completed

# MCP servers (known integrations)
mcp_servers:
  - context7            # Documentation search
  - sky-cli             # Project management
  - github              # GitHub integration
  - figma               # Design system
  - telegram-docs       # Telegram API docs
