# Skill Runtime Enums
# SSOT for runtime-specific enum values
# Shared enums (statuses, lifecycles): ../shared/enums.yaml

# Skill scopes
scopes:
  - project             # Project-local skill
  - global              # Available globally

# Document lifecycle triggers
triggers:
  - on_activation       # When skill activates
  - on_create           # When document is created
  - on_complete         # When skill completes work
  - on_handoff          # When handing off to next skill
  - spec_approved       # Specification approved
  - design_complete     # Design phase complete
  - implementation_complete  # Implementation done
  - qa_signoff          # QA approved
  - user_approved       # User approved
  - user_approval       # Alias for user_approved (archives)
  - work_unit_opened    # New work unit started
  - work_unit_closed    # Work unit completed

# Validation protocols
# Definition: definitions/protocol-definitions.yaml#protocols
protocols:
  - git                 # Git protocol (branching, commits)
  - tdd                 # Test-driven development
  - tech_debt           # Tech debt tracking
  - traceability        # Requirements traceability
  - document_structure  # Document structure compliance
  - language            # Language requirements
  - handoff             # Handoff protocol

# Pre-handoff checks
# Definition: definitions/protocol-definitions.yaml#checks
checks:
  # Code quality
  - tests_pass          # All tests pass
  - lint_clean          # No lint errors
  - build_success       # Build succeeds
  - coverage_min        # Coverage threshold met
  
  # Git state
  - branch_not_main     # Not on main/master
  - branch_clean        # No uncommitted changes
  - commits_conventional # Follows conventional format
  
  # Documentation
  - docs_updated        # Docs updated
  - changelog_updated   # CHANGELOG.md updated
  - work_unit_registry_updated  # Work unit tracked
  
  # Workflow
  - handoff_doc_created # Handoff document exists
  - approval_received   # Required approvals
  - artifact_registry_updated # Registry updated

# MCP servers (known)
mcp_servers:
  - context7            # Documentation search
  - sky-cli             # Project management
  - github              # GitHub integration
  - figma               # Design system
  - telegram-docs       # Telegram API docs
